import ContactDetails from '@/components/ContactUs/ContactDetail/page';
import ContactUsBanner from '@/components/ContactUs/ContactUsBanner/page';
import { Metadata } from 'next';
import React from 'react';
export const metadata: Metadata = {
    title: "Contact Us - Safe Ledger",
    description: "Generated by create next app",
  };
  
 const Contactus = () => {
    return (
        <>
            <ContactUsBanner />
            <ContactDetails />
        </>
    )
}
export default Contactus;