import React from 'react';
import { ServicesMainland } from '@/components/Services/ServicesMainland/page';
import { ServicesBenefits } from '@/components/Services/ServicesBenefits/page';
import { ServicesTypes } from '@/components/Services/ServicesTypes/page';
import { ServicesClassification } from '@/components/Services/ServicesClassification/page';
import { ServicesEstablish } from '@/components/Services/ServicesEstablish/page';
import { ServicesMandatory } from '@/components/Services/ServicesMandatory/page';
import { ServicesAssist } from '@/components/Services/ServicesAssist/page';
import { ServicesContact } from '@/components/Services/ServicesContact/page';
import ServiceBanner from '@/components/Services/ServiceBanner/page';
import Faq from '@/components/Services/FAQ’s/page';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Services - Safe Ledger",
    description: "Generated by create next app",
  };
  

const Service = ({ params }: { params: { slug: string } }) => {
    const slug  = params.slug; // Assuming you're using useParams to get the slug from the URL
    let jsonData = null;
    // Load different JSON files based on slug
    switch (slug) {
        case '1':
            jsonData = require('../../../public/json/services/service1.json');
            break;
        // case '2':
        //     jsonData = require('../../../public/json/services/service2.json');
        //     break;
        // case '3':
        //     jsonData = require('../../../public/json/services/service3.json');
        //     break;
        default:
            // Handle default case
            break;
    }
    return (
        <div>
            <ServiceBanner Data={jsonData.London_Registered_Office} />
            <ServicesMainland />
            <ServicesBenefits />
            <ServicesTypes />
            <ServicesClassification />
            <ServicesEstablish />
            <ServicesMandatory />
            <ServicesAssist />
            <ServicesContact />
   
            <Faq />
        </div>
    );
};

export default Service;
